server:
  port: 10000

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/gulimall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alicloud:
      access-key: LTAI5tLXifmA8RPYPvvcqCui
      secret-key: D5tVQePpZiAeajdeV5JSFrvqXAqa8S
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
  application:
    name: gulimall-product

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto #主键自增
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.study.gulimall.product.dao: debug






